import{S as d,i}from"./assets/vendor-46aac873.js";(function(){const r=document.createElement("link").relList;if(r&&r.supports&&r.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))o(e);new MutationObserver(e=>{for(const a of e)if(a.type==="childList")for(const s of a.addedNodes)s.tagName==="LINK"&&s.rel==="modulepreload"&&o(s)}).observe(document,{childList:!0,subtree:!0});function n(e){const a={};return e.integrity&&(a.integrity=e.integrity),e.referrerpolicy&&(a.referrerPolicy=e.referrerpolicy),e.crossorigin==="use-credentials"?a.credentials="include":e.crossorigin==="anonymous"?a.credentials="omit":a.credentials="same-origin",a}function o(e){if(e.ep)return;e.ep=!0;const a=n(e);fetch(e.href,a)}})();const u="41511602-ac1f0d864a13fd01c911f294b",m=document.querySelector(".search-form"),c=document.querySelector(".gallery"),f=new d(".gallery a",{captionsData:"alt",captionDelay:250}),l=document.querySelector(".loader");l.style.display="none";m.addEventListener("submit",p);function p(t){t.preventDefault();const r=t.target.elements.searchQuery.value.trim();if(!r){i.warning({title:"Warning!",message:"Please enter image name!",position:"topRight"});return}y(),l.style.display="block";const n=new URLSearchParams({key:u,q:r,image_type:"photo",orientation:"horizontal",safesearch:!0});fetch(`https://pixabay.com/api/?${n}`).then(o=>{if(l.style.display="none",!o.ok)throw new Error(o.status);return o.json()}).then(o=>{if(o.hits.length===0){i.error({message:"Sorry, there are no images matching your search query. Please try again!",position:"topRight",color:"#EF4040"});return}h(o.hits),f.refresh()}).catch(o=>{console.error("Error fetching images:",o),i.error({message:"Failed to fetch images. Please try again later.",position:"topRight"})})}function h(t){const r=document.createDocumentFragment();t.forEach(n=>{const o=g(n);r.appendChild(o)}),c.appendChild(r)}function g(t){const r=document.createElement("div");return r.classList.add("card"),r.innerHTML=`
    <a class="gallery-link" href="${t.largeImageURL}">
        <img class="card-image" src="${t.webformatURL}" alt="${t.tags}" loading="lazy">
      </a>
      <div class="card-info">
        <p class="card-text"><b>Likes:</b> ${t.likes}</p>
        <p class="card-text"><b>Views:</b> ${t.views}</p>
        <p class="card-text"><b>Comments:</b> ${t.comments}</p>
        <p class="card-text"><b>Downloads:</b> ${t.downloads}</p>
      </div>
    `,r}function y(){c.innerHTML=""}
//# sourceMappingURL=commonHelpers.js.map
